// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fouxy-landing/DarkMinimal.tsx": () => import("../components/mockups/fouxy-landing/DarkMinimal.tsx"),
  "./components/mockups/fouxy-landing/Editorial.tsx": () => import("../components/mockups/fouxy-landing/Editorial.tsx"),
  "./components/mockups/fouxy-landing/SoftAiry.tsx": () => import("../components/mockups/fouxy-landing/SoftAiry.tsx"),
  "./components/mockups/fouxy-landing/SponsorA.tsx": () => import("../components/mockups/fouxy-landing/SponsorA.tsx"),
  "./components/mockups/fouxy-landing/SponsorB.tsx": () => import("../components/mockups/fouxy-landing/SponsorB.tsx"),
  "./components/mockups/fouxy-landing/SponsorC.tsx": () => import("../components/mockups/fouxy-landing/SponsorC.tsx")
};
